on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mlr-org/_gallery/2021-01-20-keras/**'
  pull_request:
    branches:
      - main
    paths:
      - 'mlr-org/_gallery/2021-01-20-keras/**'

name: 2021-01-20-keras

jobs:
  render-post:
    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render Post
        run: |
          file = file.path("mlr-org", "_gallery", "2021-01-20-keras", paste0("2021-01-20-keras", ".Rmd"))
          rmarkdown::render(file, encoding = "UTF-8", params = list(eval_all = FALSE))
        shell: Rscript {0}

      - name: Commit Results
        if: ${{ github.event_name == 'push' }}
        run: |
          rm -f .github/workflows/pkg.lock
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m 'refactor: render 2021-01-20-keras'
          git push origin
      
      - name: Build Website
        run: rmarkdown::render_site(input = "mlr-org", encoding = "UTF-8")
        shell: Rscript {0}

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: mlr-org/docs
          single-commit: true
